# Site
name: 'CodeSyariah'
description: 'Script again Coffee again'
logo: '/assets/images/codesyariah.png'
favicon: '/assets/images/codesyariah.png'
baseurl: ''
url: 'https://codesyariah122.github.io'
disqus: 'codesyariah122-github-io'
email: 'codesyariah122@hotmail.com'
repositories: 
    repo1:
      url: https://github.com/codesyariah122/codesyariah122-github-io-repo.git

mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

collections:
  - projects

include: ["_pages"]
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: puji
      avatar: /assets/images/mypic.jpeg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 9



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
