# Site
name: 'CodeSyariah'
description: 'Script again Coffee again'
logo: '/assets/images/codesyariah.png'
favicon: '/assets/images/codesyariah.png'
baseurl: ''
developer: 'Puji Ermanto'
developeremail: 'pujiermanto@gmail.com'
dev_img: '/assets/images/codesyariah-team.gif'
url: 'https://codesyariah122.github.io'
portfolio: 'https://pujiermanto.netlify.app'
disqus: 'codesyariah122-github-io'
email: 'pujiermanto@hotmail.com'
repositories: 
    repo1:
      url: https://github.com/codesyariah122/codesyariah122-github-io-repo.git

mailchimp-list: 'http://eepurl.com/gEvV-f'

feedburner: 'https://feedburner.google.com/fb/a/mailverify'

collections:
  - projects
  - myrooms
  - cupcakes
  - cookies
  - webdevs

include: ["_pages"]
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: puji
      avatar: /assets/images/mypic.jpeg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 7

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
