# Site
name: 'CodeSyariah'
description: 'Script again Coffee again'
logo: '/assets/images/codesyariah.png'
favicon: '/assets/images/codesyariah.png'
baseurl: ''
url: 'https://codesyariah122.github.io'
disqus: 'codesyariah122-github-io'
email: 'codesyariah122@hotmail.com'
repo: https://github.com/codesyariah122/codesyariah122.github.io

mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /blog/:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    puji:
      name: PujiErmanto
      site: https://codesyariah122.github.io
      avatar: /assets/images/bio/uji.jpg
      bio: "freelancer web developer dan pendiri dari codesyariah"
      email: pujiermanto@gmail.com
      twitter: https://twitter.com/pujiermanto

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: puji
      avatar: /assets/images/mypic.jpeg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 3



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
